---
settings:
  name: ONTAP tools for VMware vSphere 10.1
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Herramientas de ONTAP para documentos de VMware vSphere 10,1
    url: "/index.html"
  - title: Notas de la versión
    url: "/release-notes.html"
  - section: concepts
  - section: deploy
  - section: configure
  - section: protect
  - section: manage
  - section: upgrade
  - section: migrate
  - section: automation
  - title: Avisos legales
    url: "/legal-notices.html"
