---
permalink: deploy/config-limits.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: Límites de configuración para poner en marcha herramientas de ONTAP para VMware vSphere 
---
= Límites de configuración para poner en marcha herramientas de ONTAP para VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar la siguiente tabla como guía para configurar herramientas de ONTAP para VMware vSphere.

|===


| *Despliegue* | *Tipo* | *Número de vVols* | *Número de hosts* | *Tipo de protocolo* 


| Puesta en marcha sencilla | Pequeño (S) | ~12K | 32 | NFS, iSCSI 


| Puesta en marcha sencilla | Medio (M) | ~24K | 64 | NFS, iSCSI 


| Alta disponibilidad | Pequeño (S) | ~24K | 64 | NFS, iSCSI 


| Alta disponibilidad | Medio (M) | ~50k | 128 | NFS, iSCSI 


| Alta disponibilidad | Grande (L) | ~100k | 256 [NOTA] El número de hosts de la tabla muestra el número total de hosts de varios vCenter. | NFS, iSCSI 
|===
Para obtener más información acerca de los requisitos de tamaño del sistema host por nodo, consulte link:../deploy/sizing-requirements.html["Requisitos previos para implementar herramientas de ONTAP para VMware vSphere"].



== Herramientas de ONTAP para VMware vSphere: Storage Replication Adapter (SRA)

La siguiente tabla muestra los números admitidos por instancia de SRM con herramientas de ONTAP para VMware vSphere.

|===
| *Tamaño de implementación de vCenter* | *Pequeño* | *Media* 


| Cantidad total de máquinas virtuales configuradas para la protección mediante la replicación basada en cabinas | 2000 | 5000 


| Número total de grupos de protección de replicación basados en cabinas | 250 | 250 


| Número total de grupos de protección por plan de recuperación | 50 | 50 


| Número de almacenes de datos replicados | 255 | 255 


| Número de máquinas virtuales | 4000 | 7000 
|===
La siguiente tabla muestra el número de SRM y las herramientas de ONTAP correspondientes para el tamaño de puesta en marcha de VMware vSphere.

|===


| *Número de instancias SRM* | *ONTAP herramientas de implementación Tamaño* 


| Hasta 4 | Pequeño 


| 4 a 8 | Mediano 


| Más de 8 | Grande 
|===
Para obtener más información, consulte https://docs.vmware.com/en/VMware-Live-Recovery/services/vmware-live-site-recovery/GUID-3AD7D565-8A27-450C-8493-7B53F995BB14.html["Límites operativos de Live Site Recovery de VMware"].
