---
permalink: deploy/recovery-deployment.html 
sidebar: sidebar 
keywords:  
summary: Si pierde sus herramientas de ONTAP para la configuración de VMware vSphere, pero tiene su ONTAP funcionando, puede recuperar las herramientas de ONTAP para la configuración de VMware vSphere mediante ONTAP. Cuando pierda la configuración, elimine la configuración correctamente. 
---
= Recupere sus herramientas de ONTAP para la configuración de VMware vSphere
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si pierde sus herramientas de ONTAP para la configuración de VMware vSphere, puede recuperar las herramientas de ONTAP para la configuración de VMware vSphere con los datos disponibles en los datos del volumen de ONTAP. Cuando pierda la configuración, elimine la configuración correctamente.


NOTE: No puede recuperar las herramientas de ONTAP para la configuración de VMware vSphere si hay problemas con vCenter Server o el software de gestión de datos ONTAP.

* Pasos*

. Inicie sesión en vSphere Server.
. Desplácese hasta el pool de recursos, el clúster del nodo o el host donde desea implementar el OVA.
. Haga clic con el botón derecho en la ubicación requerida y seleccione *Implementar plantilla OVF*.
. Puede introducir la URL del archivo _.ova_ o navegar hasta la carpeta donde se guarda el archivo _.ova_ y, a continuación, seleccionar *Siguiente*.
+

NOTE: Debe utilizar la misma compilación OVA que utilizó para instalar la configuración de recuperación.

. Seleccione un nombre y una carpeta para la máquina virtual y seleccione *Siguiente*.
. Seleccione el host y seleccione *Siguiente*.
. Revisa el resumen de la plantilla y selecciona *Siguiente*.
. Lea y acepte el contrato de licencia y seleccione *Siguiente*.
. En la ventana *Configuración*, selecciona la opción *Recuperación*.
. En la ventana *Seleccionar almacenamiento*, seleccione el almacenamiento para las configuraciones y los archivos de disco.
. En la ventana *Seleccionar redes*, seleccione una red de destino para cada red de origen.
+

NOTE: Es necesario conservar la dirección IP del balanceador de carga y la dirección IP de Kubernetes API Server. Se puede cambiar la dirección IP del nodo o conservar la misma dirección IP.

. Selecciona *Personalizar plantilla* > *configuración del sistema* ventana. Introduzca los siguientes detalles:
+
.. Nombre de usuario y contraseña de aplicación: Este nombre de usuario y contraseña se utilizan para registrar tanto el proveedor de VASA como el SRA en vCenter Server. Puede ser diferente del nombre de usuario y la contraseña proporcionados durante la implementación inicial.
.. La casilla de verificación *Activar ASUP* está seleccionada de forma predeterminada.




AutoSupport solo se puede habilitar o deshabilitar durante la implementación. .. En el campo *URL de proxy ASUP*, proporcione esta URL para evitar el bloqueo del firewall para la transmisión de datos AutoSupport. .. Nombre de usuario del administrador y contraseña del administrador: Esta es la contraseña utilizada para iniciar sesión en el Administrador de herramientas de ONTAP. Puede ser diferente del nombre de usuario y la contraseña proporcionados durante la implementación inicial. .. Ingrese la información de su servidor NTP en el campo *Servidores NTP*. .. Contraseña de usuario de mantenimiento: Se utiliza para otorgar acceso a las opciones de la consola de mantenimiento. . En la ventana *Personalizar plantilla* > *Configuración de implementación*, introduzca los detalles proporcionados durante la implementación. Todos los valores de esta sección deben ser iguales que los proporcionados durante la puesta en marcha inicial, excepto el valor de la LIF de datos.


NOTE: No se debe cambiar el nombre de la SVM de almacenamiento, ya que es donde se almacenan los datos de recuperación. Esto se aplica a la cuenta de usuario de SVM que se añade directamente también. . En el caso de la recuperación HA-despliegue, proporcione los siguientes detalles: .. Detalles de la biblioteca de contenido. .. Detalles de configuración de vCenter. . En la ventana *Personalizar plantilla* > *Configuración del nodo*, introduzca los detalles según la configuración que está intentando recuperar, configuración no HA o HA. . Revise los detalles en la ventana *Listo para completar*, seleccione *Finalizar*.

+ A medida que se crea la tarea de puesta en marcha, el progreso se muestra en la barra de tareas de vSphere. . Encienda la máquina virtual después de completar la tarea.

+ Comienza la instalación. Puede realizar un seguimiento del progreso de la instalación en la consola web de VM. Como parte de la instalación, se validan las configuraciones de los nodos. Se validan las entradas proporcionadas en diferentes secciones de la plantilla Personalizar en el formulario OVF. En caso de discrepancias, un cuadro de diálogo le solicita que realice una acción correctiva. . Realice los cambios necesarios en el indicador de diálogo. Utilice el botón Tab para navegar por el panel e ingresar sus valores, *OK* o *Cancel*. . Al seleccionar *OK* o *Cancel*, los valores proporcionados se volverán a validar. Las herramientas de ONTAP para VMware permiten tres intentos de corregir los valores no válidos. Si no puede corregir los problemas después de tres intentos, la instalación del producto se detiene y se recomienda que intente la instalación en una máquina virtual nueva. . Después de la instalación correcta, la consola web muestra el estado de las herramientas de ONTAP para VMware vSphere. Después de una instalación correcta, debe editar manualmente los requisitos de hardware según las directrices de link:../deploy/sizing-requirements.html["Requisitos previos para implementar herramientas de ONTAP para VMware vSphere"] la página.
