---
permalink: protect/enable-storage-replication-adapter.html 
sidebar: sidebar 
keywords:  
summary: Las herramientas de ONTAP para VMware vSphere ofrecen la opción de habilitar la funcionalidad del SRA de configurar la recuperación ante desastres. 
---
= Habilite SRA para proteger almacenes de datos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las herramientas de ONTAP para VMware vSphere ofrecen la opción de habilitar la funcionalidad del SRA de configurar la recuperación ante desastres.

*Lo que necesitará*

* Debe haber configurado la instancia de vCenter Server y el host ESXi.
* Debe haber puesto en marcha las herramientas de ONTAP.
* Debería haber descargado `.tar.gz` el archivo SRA Adapter de la https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["Sitio de soporte de NetApp"^].


* Pasos*

. Inicie sesión en la interfaz de gestión de dispositivos SRM mediante la URL `\https://:<srm_ip>:5480`: Y, a continuación, vaya a Adaptadores de replicación de almacenamiento en la interfaz de gestión de dispositivos VMware SRM.
. Seleccione *Nuevo adaptador*.
. Cargue el instalador _.tar.gz_ del plugin de SRA en SRM.
. Vuelva a analizar los adaptadores para verificar que los detalles se hayan actualizado en la página SRM Storage Replication Adapters.

