---
sidebar: sidebar 
permalink: automation/get-started-with-the-rest-api.html 
keywords: REST API 
summary: El acceso a la API ofrece una cierta perspectiva antes de comenzar a utilizarla con los procesos de flujos de trabajo más complejos en una configuración en directo. 
---
= Comience con la API DE REST
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Es posible empezar a usar rápidamente las herramientas de ONTAP para la API de REST DE VMware vSphere. El acceso a la API ofrece una cierta perspectiva antes de comenzar a utilizarla con los procesos de flujos de trabajo más complejos en una configuración en directo.



== Hola Mundo

Puede ejecutar un sencillo comando en su sistema para comenzar a utilizar las herramientas de ONTAP para la API de REST DE VMware vSphere y confirmar su disponibilidad.

.Antes de empezar
* Asegúrese de que la utilidad Curl está disponible en el sistema.
* Dirección IP o nombre de host de las herramientas de ONTAP para VMware vSphere Server
* Nombre de usuario y contraseña de una cuenta con autoridad para acceder a herramientas de ONTAP para la API de REST DE VMware vSphere.



NOTE: Si sus credenciales incluyen caracteres especiales, debe formatearlos de una forma que sea aceptable para Curl en función del shell que esté utilizando. Por ejemplo, puede insertar una barra diagonal inversa antes de cada carácter especial o ajustar toda `username:password` la cadena entre comillas simples.

.Paso
En la interfaz de línea de comandos de, ejecute lo siguiente para recuperar la información del plugin:

`curl -X GET -u username:password -k "\https://<ip_address>/api/hosts?fields=IncludePluginInfo"`

Ejemplo:

`curl -X GET -u admin:password -k "'\https://10.225.87.97/api/hosts?fields=IncludePluginInfo"`
