---
permalink: manage/manage-vcenter.html 
sidebar: sidebar 
keywords:  
summary: Las instancias de vCenter son plataformas de gestión central que le permiten controlar hosts, equipos virtuales y back-ends de almacenamiento. 
---
= Gestione la instancia de vCenter Server
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Las instancias de vCenter Server son plataformas de gestión central que permiten controlar hosts, máquinas virtuales y back-ends de almacenamiento.



== Asocie o disocie los back-ends de almacenamiento con la instancia de vCenter Server

La página enumerada de vCenter Server muestra el número asociado de back-ends de almacenamiento. Cada instancia de vCenter Server tiene la opción de asociar o desasociar un back-end de almacenamiento. Esta tarea le ayuda a crear una asignación entre el back-end de almacenamiento y la instancia incorporada de vCenter Server a nivel global.

* Pasos*

. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://loadBalanceIP:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione vCenter Server Instances en la barra lateral.
. Haga clic en los tres puntos verticales en la instancia de vCenter Server que desea asociar o disociar con los back-ends de almacenamiento.
. Selecciona *Asociar o disociar backend de almacenamiento* dependiendo de la acción que quieras realizar.




== Modifique la instancia de vCenter Server

Siga los pasos a continuación para modificar las instancias de vCenter Server.

. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://loadBalanceIP:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione vCenter Server Instances en la barra lateral
. Haga clic en los tres puntos verticales en el vCenter Server que desea modificar y seleccione *Modificar*.
. Modifique los detalles de la instancia de vCenter Server y seleccione *Modify*.




== Quite la instancia de vCenter Server

Debe quitar todos los back-ends de almacenamiento conectados a vCenter Server antes de quitarlos.

. Inicie ONTAP TOOLS Manager desde un explorador web: `\https://loadBalanceIP:8443/virtualization/ui/`
. Inicie sesión con las herramientas de ONTAP para las credenciales de administrador de VMware vSphere que proporcionó durante la implementación.
. Seleccione vCenter Server Instances en la barra lateral
. Haga clic en los puntos suspensivos verticales contra el vCenter Server que desea quitar y seleccione *Quitar*.
+

NOTE: Una vez que se quitan las instancias de vCenter Server, la aplicación ya no lo mantendrá.


